import { Component } from '@angular/core';

// Importing dummy users
import { DUMMY_USERS } from '../dummy-users';

// Having a random number generated, based on the Dummy Users collection
const randomIndex = Math.floor(Math.random() * DUMMY_USERS.length);

@Component({
  selector: 'app-user',
  imports: [],
  templateUrl: './user.html',
  styleUrl: './user.scss',
})
export class UserComponent {
  // Will display the random user, but how to use it in the template?
  selectedUser = DUMMY_USERS[randomIndex];

  // Note: when adding "private" to selectedUser, it won't be accessible in the template, only in the class.
  // So by not adding private, it will automatically be public.

  // When it comes to outputting dynamic content in Angular applications, you get 2 main ways of binding your template or parts of your template,
  // to values generated by the component class.
  // Therefore, in order to display selectedUser in the template:

  // 1 - String interpolation: {{ selectedUser.<any property of the selectedUser> }}
  // ex: <span>{{ selectedUser.name }}</span>

  // 2 - Property binding:
  // ex: <img [src]="selectedUser.avatar" [alt]="selectedUser.name"/>

  // Getter for Computed Value (better to use that here instead of the template to make it cleaner)
  get imagePath() {
    return 'assets/users/' + this.selectedUser.avatar;
  }
}
